AWSTemplateFormatVersion: "2010-09-09"
Description: Combined CloudFormation Template for Big Data Lab with Kafka, Glue, and S3 Integration.
Parameters:
  KafkaBootstrapServers:
    Type: String
    Description: Kafka bootstrap servers (e.g., broker1:9092,broker2:9092).
    Default: '10.0.1.50:9092'
  KafkaTopicName:
    Type: String
    Description: Name of the Kafka topic to read messages from.
    Default: "market_tickers_data"
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket to store data.
    Default: 'basic-stack-s3bucket-fxxrjdrgc3w6'
  GlueDatabaseName:
    Type: String
    Description: Name of the Glue database to store data.
    Default: 'market_db'
  PublicSubnet:
    Type: String
    Description: Public subnet ID for Glue job.
    Default: 'subnet-09695c37364200015'
  VPCId:
    Type: String
    Description: VPC ID where the Glue job and endpoint will be created.
    Default: 'vpc-05d85edc8aa9101b5'

Resources:
  CommandRunner:
    Type: AWSUtility::CloudFormation::CommandRunner
    Properties:
      Command: 
        "Fn::Join": [
          '', [
            aws s3 cp ../scripts/kafka_to_s3.py s3://,
            Ref: S3BucketName,
            "/scripts/kafka_to_s3.py"
          ]
        ]
        
  # Security Group for Glue
  PublicSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow all inbound traffic to Glue"
      VpcId: 
        Ref: VPCId
      SecurityGroupIngress:
        - IpProtocol: "-1"  # -1 allows all protocols
          FromPort: "0"     # 0 to 65535
          ToPort: "65535"    # 0 to 65535
          CidrIp: "0.0.0.0/0"  # Allow from all IPs

  # Glue Resources
  GlueDatabase:
    Type: "AWS::Glue::Database"
    Properties:
      CatalogId: 
        Ref: "AWS::AccountId"
      DatabaseInput:
        Name: 
          Ref: GlueDatabaseName

  GlueConnection:
    Type: "AWS::Glue::Connection"
    Properties:
      CatalogId: 
        Ref: "AWS::AccountId"
      ConnectionInput:
        Name: "KafkaConnection"
        ConnectionType: "KAFKA"
        PhysicalConnectionRequirements:
          AvailabilityZone: 
            Fn::Select: 
              - 0
              - Fn::GetAZs: ""
          SubnetId: 
            Ref: PublicSubnet
          SecurityGroupIdList: [
            Ref: PublicSecurityGroup
          ]
        ConnectionProperties:
          KAFKA_BOOTSTRAP_SERVERS: 
            Ref: KafkaBootstrapServers
          KAFKA_TOPIC_NAME: 
            Ref: KafkaTopicName

  GlueJob:
    Type: "AWS::Glue::Job"
    Properties:
      Name: "KafkaToS3Job"
      Role: "LabRole"
      Command:
        Name: "glueetl"
        ScriptLocation: 
          Fn::Sub: "s3://${S3BucketName}/scripts/kafka_to_s3.py"
        PythonVersion: "3"
      DefaultArguments:
        "--TempDir": 
          Fn::Sub: "s3://${S3BucketName}/temp/"
        "--job-bookmark-option": "job-bookmark-enable"
        "--KAFKA_TOPIC_NAME": 
          Fn::Sub: "${KafkaTopicName}"
        "--S3_OUTPUT_PATH": 
          Fn::Sub: "s3://${S3BucketName}/output/"
      GlueVersion: "2.0"
      Timeout: 2880
      MaxRetries: 1

  GlueVpcEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      ServiceName: "com.amazonaws.us-east-1.glue"
      VpcId:  
        Ref: VPCId
      SubnetIds:
        - Ref: PublicSubnet
      SecurityGroupIds:
        - Ref: PublicSecurityGroup
      VpcEndpointType: "Interface"

Outputs:
  GlueDatabaseName:
    Description: Glue Database Name
    Value: 
      Ref: GlueDatabase
  GlueJobName:
    Description: Glue Job Name
    Value: 
      Ref: GlueJob